### ISSUE TITLE
Installation via `poetry` takes forever... or fails

### ISSUE THREAD

**Issue by JJ** [EC-KitY/EC-KitY#111]
**Describe the bug**

For the time being, > 300s resolving dependencies for a fresh install.

**To Reproduce**

1. Initialize a poetry file via `poetry init`
2. `poetry add eckity`

It either takes a long time or fails with `Installing numpy (1.19.5): Failed`

**Expected behavior**

It should add `eckity` to the list of dependencies

**Python (please complete the following information):**
 - Version 3.10.5 and 3.12.3

**Additional context**

This is probably `numpy`' s fault. However, `poetry` is the main way of installing modules nowadays (together with hash), so it might be worth the while to document to discourage it.

**Comment by JJ** [comment]
OK, the issue is it does not work with Python > 3.11

Solved with 

```
python = ">=3.9,<3.11"
```

Might be worth the while to document it, though. Can create a PR if desired.

**Comment by achiyae** [comment]
Thank, @JJ, for the quick catch. I think we will take it from here because it might be the time to extend the language support...

**Comment by itaitzruia4** [comment]
Solved in #112 
Thanks!
