### ISSUE TITLE
Fix for uniform mutation

### ISSUE THREAD

**Issue by eliadsbgu** [EC-KitY/EC-KitY#128]
```python class IntVectorUniformMutation(VectorNPointMutation):
    """
    Uniform N Point Integer Mutation
    """

    def __init__(self, probability=0.5, arity=1, events=None, probability_for_each=0.1):
        self.probability_for_each = probability_for_each
        super().__init__(probability=probability,
                         arity=arity,
                         mut_val_getter=lambda individual, index: individual.get_random_number_in_bounds(
                             index) if random() <= self.probability_for_each else individual.cell_value(index),
                         events=events, cell_selector=uniform_cell_selector)

**Comment by achiyae** [comment]
Please create a pull request

**Comment by itaitzruia4** [comment]
> Please create a pull request and add explanation why it is needed

In practice, this change caused Eliad's algorithm to converge, while the current version kept it in a local minima.
The existing approach for Int and Float vector mutations chooses exactly N points and mutates their value, while in bit vectors the mutation traverses all cells and flips each of them with some probability.
Eliad suggests to change the IntVectorMutation to be more similar to the bit vector mutation.

**Comment by achiyae** [comment]
Hmm, I agree it should be implemented like eliad suggested
