### ISSUE TITLE
Error in import in Sklearn compatible breast cancer tutorial

### ISSUE THREAD

**Issue by zahidirfan** [EC-KitY/EC-KitY#30]
`from eckity.sklearn_compatible.sk_classifier import SkClassifier
`
This line should be.
`from eckity.sklearn_compatible.sk_classifier import SKClassifier
`

The link to the wiki : 
https://github.com/EC-KitY/EC-KitY/wiki/Tutorial:-Sklearn--Compatible-Breast-Cancer

**Comment by itaitzruia4** [comment]
Thanks for pointing it out, I've updated the Wiki page.
