### ISSUE TITLE
final mathematical expression

### ISSUE THREAD

**Issue by MohammadSoltani100** [EC-KitY/EC-KitY#34]
Hi

How to extract final mathematical expression in "Sklearn Compatible Symbolic Regression"?

**Comment by itaitzruia4** [comment]
Hi, 
Currently, there's no support for converting GP Trees into mathematical expressions, but the implementation should be pretty straightforward.

Trees are represented as lists, where the children of each node are the following elements in the list, according to its arity.

For example, the expression `(x + y) * (z - w)` will be represented as `[f_mul, f_add, x, y, f_sub, z, w]`
