### ISSUE TITLE
Tiny bugfix - `best_of_run_` assignment in the first generation

### ISSUE THREAD

**Issue by itaitzruia4** [EC-KitY/EC-KitY#45]
`simple_evolution.py`, line 152:
`best_of_run_` field should be `best_of_gen` in the first generation.

the line 
```python
if self.best_of_gen.better_than(self.best_of_run_):
```
should be changed to
```python
if self.best_of_run_ is None or self.best_of_gen.better_than(self.best_of_run_):
```

**Comment by lior8** [comment]
But doesn't better_than() function of an individual already returns true for the case that the parameter is None?
