### ISSUE TITLE
Add `verboose` field to `Algorithm` class

### ISSUE THREAD

**Issue by itaitzruia4** [EC-KitY/EC-KitY#46]
add a boolean `verboose` field that will only print `debug: random seed...` and end of run results if `verboose=True`

**Comment by deepgohil** [comment]
I would like to solve this issue. Can you tell me how to do it?

**Comment by itaitzruia4** [comment]
Thank you!
add a constructor argument to `Algorithm` and its sub-classes,
change line 212 in `algorithm.py` to only print if `verboose` is True
and modify the method `finish()` in `simple_evolution.py` to also print only if `verboose` is True.

**Comment by lior8** [comment]
Is this issue still being worked on? Or can I submit a PR for it?
